### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by E3V3A** [E3V3A/iata-arrivals-cli#1]
A few things left t do:

- [ ] Fix "-j" CLI flag for debug mode
- [x] Fix for some ambigous country names ("United" for UK,US,USA, UAE)
- [ ] Fix tabulation by using `.format` and `.l/rjust` instead of all in-string TAB's.
- [ ] Fix a potential coloring problem for Windows (is TERM a color term?)
- [x] Add "-n" CLI flag to limit output to <n> number of flights/airports
- [ ] Add "-a" CLI flag to add API credentials by supplying a registered email and password
- [ ] Add "-t" CLI flag for time-zone (TZ) times used for API vs. local airport TZ
- [ ] Add "-f" CLI flag for getting history of a certain flight:  
   `api.get_history_by_flight_number('AI101')[-5:]`
- [ ] Add alternative source(s) for other airports not available 
- [x] UI: Truncate decimals in the airport `Visibility`  field (conversion issue?)  
 (A great first issue to fix, if you'd like to contribute.)

**Comment by E3V3A** [comment]
* [ ] Fix "-i" for unknown IATA code
* [ ] Investigate how to implement ICAO -- 4 letter airpiort codes
* [ ] Fix tabulation by using {} formatting instead of all in-string TAB's
* [ ] Fix color check also for:  xterm-color and xterm-256color etc.
* [ ] Add gate number to Departures
* [ ] Add "-r" CLI flag to get Flightradar24 current flights within boundary box,  
      given a [lat/lon] (decimal degrees) and radius in km. I.e.:  
      arrivals -r <lat,lon> <radius[km]>   
      See:    
      1. [MMM-FlightsAbove](https://github.com/E3V3A/MMM-FlightsAbove)  
      2. [flightradar24-client](https://github.com/derhuerst/flightradar24-client) 
* [-] Add RealFeel temperature calulation from realfeel.py
* [ ] ^^^ ~~We use FeelsLike (from meteocalc) instead~~ as RealFeel is too complicated and poorly documented.  
      - https://github.com/malexer/meteocalc  
      I rewrote the *Feels Like* to correct some bugs and make things simple in `SI` units.
      - https://gist.github.com/E3V3A/8f9f0aa18380d4ab2546cd50b725a219
